service: ddbimport

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  memorySize: 2048 # optional, in MB, default is 1024
  timeout: 900 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  runtime: go1.x
  stage: dev
  region: eu-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  ddbimport:
    handler: bin/ddbimport
